### ISSUE TITLE
Feature request: Velocity Support

### ISSUE THREAD

**Issue by femboyfin** [SlimeDog/NetworkInterceptor#13]
**Is your feature request related to a problem? Please describe.**
Velocity support is a growing proxy platform separate from BungeeCord that is [gaining popularity](https://bstats.org/global/velocity) and has already seen adoption from some large networks like [TheArchon](https://thearchon.net). Some server owners (including myself) have had interest in moving in the past to Velocity but were deterred by a lack of plugin support, creating a rather large barrier to entry. However, I have recently seen more and more plugins adopt support for Velocity and I'm looking forward to having the option to move to Velocity in the (hopefully-near) future. Adding support for Velocity (while it is an albeit small platform compared to BungeeCord) could definitely prove beneficial to many server owners. Assuming Velocity keeps growing at the rate it is, it isn't that unlikely that there will be more server owners interested in moving to Velocity that could be held back by a lack of plugin support.

**Describe the solution you'd like**
I'd like for velocity support to eventually be added to NetworkInterceptor.

**Describe alternatives you've considered**
There is always the alternative of staying with BungeeCord or simply running a Velocity network without NetworkInterceptor on the proxy and only on the Spigot backends but these both have drawbacks. Velocity has a number of benefits over BungeeCord that for the sake of brevity I won't list but I'll link to them [here](https://velocitypowered.com/wiki/users/what-does-velocity-do-for-me) which makes sticking with BungeeCord a drawback in and of itself. Running a network where the proxy doesn't have NetworkInterceptor has the obvious drawback of not having NetworkInterceptor, this is a really useful plugin and there aren't any good alternatives that I've been able to find for Velocity.

**Additional context**
It's definitely worth noting that the numbers Velocity has compared to BungeeCord are not very high and while I do urge you to compare the growth of both proxies as well as their servers-to-players ratios, I understand if this is held at lower priority.
I should also mention that I am interested in (and am actively) learning more about how Velocity differs from BungeeCord and I'd be happy to share what I find to help the process along- I believe this plugin should be available for everyone, regardless of platform.

**Comment by SlimeDog** [comment]
Velocity is outside the current scope of the project. Given that NetworkInterceptor is open-source, there are several possible paths forward:
- Under the [Unlicense](https://github.com/SlimeDog/NetworkInterceptor/blob/master/LICENSE.txt), anyone is free to fork the project and extend it to include Velocity. 
- We would be amendable to a well-designed, coded and tested PR submission, with the goal of incorporating the code.
- We would consider doing the work, given a substantial contribution to fund the design, development and testing.

**Comment by femboyfin** [comment]
> * We would consider doing the work, given a substantial contribution to fund the design, development and testing.

Of monetary nature, correct?

**Comment by SlimeDog** [comment]
Please open a SpigotMC PM to discuss. We flooded the Bungee feature request with too much chatter.

**Comment by SlimeDog** [comment]
Implemented in version 3.1.2
