### ISSUE TITLE
setSecurityManager will be removed in a future release

### ISSUE THREAD

**Issue by HexedHero** [SlimeDog/NetworkInterceptor#20]
**Description**
Warning on startup

**Reproduction steps**
Startup with Java 17

**Expected behavior**
No warning

**Screenshots**
N/A

**Server Environment**
 - OS [Linux, MacOS, Windows] version: N/A
 - Java version [java -version]: 17
 - Server version [/version]: his server is running Paper version git-Paper-400 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4ac995a on ver/1.17.1)
 - NetworkInterceptor version [/version NetworkInterceptor]: 3.1.5

**Additional context**
 Link to your configuration: Default
 Link to error log:
[12:26:41 INFO]: [NetworkInterceptor] Interceptors: [security-manager, proxy-selector]
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor (file:/home/minecraft/server/plugins/NetworkInterceptor-3.1.5.jar)
WARNING: Please consider reporting this to the maintainers of me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor

WARNING: System::setSecurityManager will be removed in a future release

**Comment by SlimeDog** [comment]
Duplicate #16
