### ISSUE TITLE
Tebex/CraftingStore in defaults

### ISSUE THREAD

**Issue by HexedHero** [SlimeDog/NetworkInterceptor#22]
**Is your feature request related to a problem? Please describe.**
Tebex/CraftingStore is blocked by default with the example configs.

**Describe the solution you'd like**
Add Tebex and CraftingStore to the default configs to allow working.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm unsure if its just tebex.io or api.tebex.io and craftingstore.net or api.craftingstore.net

**Comment by SlimeDog** [comment]
The sample files are not intended to list every target that a user might want to consider. It is up to the user to configure according to their requirements.

`config.yml` and `sample-deny-config.yml` block nothing.

`sample-allow-config.yml` lists only a few generally useful targets as examples, with no intent that it should be considered inclusive.​
