### ISSUE TITLE
Feature request: Trust specific plugins

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/NetworkInterceptor#3]
It would be nice to allow connections from specific (tested and trusted) plugins to increase signal-to-noise ratio. For example, _LuckPerms_ and _Plan_ produce a lot of network connections, all of them desirable, so not necessary to include them in intercept monitoring.

**Comment by lucko** [comment]
It's hard to accurately detect a single plugin as the cause of a request - so I don't think this would be that effective or useful.

Could result in false positives.

**Comment by SlimeDog** [comment]
Hmmm. Isn't that what the stack trace does?

**Comment by SlimeDog** [comment]
We are going to address this functionality in NetworkInterceptor 2.0. More to follow.

**Comment by SlimeDog** [comment]
Release in NetworkInterceptor 2.0.0
