### ISSUE TITLE
The plugin does not run on PaperSpigot 1.16.5 

### ISSUE THREAD

**Issue by archroot** [SlimeDog/NetworkInterceptor#39]
The plugin does not run on PaperSpigot 1.16.5 
 java version 17

https://pastebin.com/3hdRLSYf

**Comment by SlimeDog** [comment]
Per the attached [error log](https://pastebin.com/3hdRLSYf), you are trying to run **NetworkInterceptor 3.3.3** on **Paper 1.16.5-794**. Per the [wiki](https://github.com/SlimeDog/NetworkInterceptor/wiki/Technical-Details),
**NetworkInterceptor 3.3.3** was certified for **Paper 1.19.4 and Spigot 1.19.4**.

It was not tested on previous versions, and is not certified to work on them. **Paper 1.16.5** is over two years old, and is no longer supported. We recommend that you update your server.
