### ISSUE TITLE
Feature request: Add api.spiget.org to default list

### ISSUE THREAD

**Issue by egg82** [SlimeDog/NetworkInterceptor#7]
api.spiget.org is used as a spigotmc.org api/parser and update check utility, and it's been around for quite some time. I suggest adding it to the default list in the config.

**Comment by SlimeDog** [comment]
**api.spigotmc.org** manages all SpigotMC.org plugin update checks.

**Comment by SlimeDog** [comment]
Will do. Look for it in 2.0.0

**Comment by SlimeDog** [comment]
Release in NetworkInterceptor 2.0.0
