### ISSUE TITLE
Can you stop dependabot

### ISSUE THREAD

**Issue by ghost** [SlimeDog/NetworkInterceptor#77]
Its annoying, and doesn't really change anything

**Comment by SlimeDog** [comment]
I don't understand why we should do that. It is useful to the developers, and has no user-facing impact.

How is it annoying?

**Comment by ghost** [comment]
> I don't understand why we should do that. It is useful to the developers, and has no user-facing impact.
> 
> How is it annoying?

I have the report forked and i have to keep fetching upstream

**Comment by mart-r** [comment]
You don't have to keep syncing every minor change. Only do so when it's relevant to you.

And if you don't care for the changes, you can omit syncing entirely until we release a new version and make the determination of whether or not you need to sync at that point.

**Comment by SlimeDog** [comment]
I don't find a fork under your handle.

You are free to do what you want, of course, but why not just deploy the current version? We don't update the releases that often.

If any event, we will not disable dependabot.
