### ISSUE TITLE
AAC-related blockage

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/NetworkInterceptor#8]
AAC has inserted new methods to attempt to thwart hacks involving NetworkInterceptor. See https://github.com/konsolas/AAC-Issues/issues/1655.  I have disabled _methods.security-manager_, which masks the issue, but (reputedly, based on the comments in the config.yml) _methods.proxy-selector_ is not as proficient at identifying outbound network calls. Can something be done about this issue?

**Comment by Janmm14** [comment]
Network interception has its good and its dark sides. AAC decided to prevent this because of the dark side possibilities.

**Comment by SlimeDog** [comment]
Understood. But AAC could give me the choice, as with most configuration options, if you explained the tradeoffs clearly. But you know more than I do.

**Comment by Janmm14** [comment]
Please watch discord private message

**Comment by SlimeDog** [comment]
I don't Discord. Please respond to Github issues on Github.

**Comment by Janmm14** [comment]
konsolas will not add a config option to basically allow leaks.

**Comment by SlimeDog** [comment]
OK. Thanks.

**Comment by Eyremba** [comment]
> konsolas will not add a config option to basically allow leaks.

How does AAC even try to block this plugin? Spigot resources which require internet access are still illegal on SpigotMC.org

**Comment by Janmm14** [comment]
@Eyremba AAC complies with spigotmc rules

**Comment by SlimeDog** [comment]
Pretty much every premium plugin accesses the internet to attempt anti-piracy protection. Piracy is illegal too, but that doesn't prevent sophisticated MC-piracy web sites from doing it.

**Comment by Eyremba** [comment]
> Pretty much every premium plugin accesses the internet to attempt anti-piracy protection. Piracy is illegal too, but that doesn't prevent sophisticated MC-piracy web sites from doing it.

@SlimeDog You didn't get my point: Enforcing internet access is forbidden by SpigotMC. If a resource does this, you can report it and SpigotMC will instantly delete the resource and ban the user who uploaded it. This happened many times before.

**Comment by lucko** [comment]
All this plugin does is *simulate* no internet connection.

> Network interception has its good and its dark sides. AAC decided to prevent this because of the dark side possibilities.

What the hell does "dark side possibilities" mean. Sounds like fear-mongering. 

The only thing I'd be concerned about is a plugin such as AAC requiring internet access for seemingly no reason? Doesn't sound like something that is necessary for the plugin to work as described.

**Comment by Eyremba** [comment]
@lucko yep, AAC uses internet connection only for licensing purposes (checking if the version is leaked and such), but the SpigotMC guidelines already say that every resource must also be able to work without internet connection, for example if you are offline.

**Comment by Janmm14** [comment]
AAC complies with the mentioned spigotmc rule. The internet connection is used for notifying when there is a newer version available. "dark side possibilities" = leakers and crackers

**Comment by SlimeDog** [comment]
AAC attempts a number of internet connections. They are **all** for update checks? If that is the case, make a configuration option to disable update checks (as most plugins do), and AAC won't care what NetworkInterceptor does.

**Comment by Janmm14** [comment]
AAC will not change. I did not say that the connection is not also for license checking.

**Comment by SlimeDog** [comment]
Strictly speaking, you were correct. _"The internet connection is used for notifying when there is a newer version available"_ implies that there is only one internet connection, and only one use of it, without actually saying that. A very lawyerly construction.

Clearly internet connections are used for both purposes. I personally don't object to the anti-piracy methods, although it's not at all clear that it's a winnable battle. I do object to rendering NetworkInterceptor less useful, but konsolas will do as he chooses.

**Comment by Eyremba** [comment]
> AAC complies with the mentioned spigotmc rule. The internet connection is used for notifying when there is a newer version available.

But it is not allowed to enforce this. SpigotMC guidelines state that it also has to work without an internet connection. How does AAC comply with this rule when enforcing the blockage of this plugin here? ;)

**Comment by Janmm14** [comment]
@Eyremba I hope you can understand that the details of the antipiracy protections will stay private.

**Comment by Eyremba** [comment]
> I hope you can understand that the details of the antipiracy protections will stay private.

@Janmm14 That's not the point. I hope that you understand that the resource has to work without an internet connection, which is obviously not the case.

**Comment by Janmm14** [comment]
@Eyremba As I already said, AAC works without an internet connection.

**Comment by Eyremba** [comment]
@Janmm14 Most likely, AAC does this by using a custom security-manager just like this plugin here. But what if I don't want that due to security reasons?

**Comment by Janmm14** [comment]
There is still the possibility to change dns resolves (for example through the hosts file) and/or using iptables. Or only use trusted plugins.

**Comment by SlimeDog** [comment]
OK, it's been a year. I hope that has been ample opportunity for the folks involved to think about this issue, and figure out a way for AAC and NetworkIntercepter to coexist. NetworkInterceptor is basically unusable without the _security-manager_ detection method. But if _security-manager_ is enabled, AAC arbitrarily disables itself.

One lives in hope. [Please do not re-flog the anti-piracy issues.]

**Comment by SlimeDog** [comment]
NetworkInterceptor has been transferred to my team. We are working on feature and functionality enhancements, which will be released in due course. Given the discussion above, we will include commentary that NetworkInterceptor and AAC are incompatible. It's sad, but that's the way it seems to be.

**Comment by SlimeDog** [comment]
NetworkInterceptor 2.0.0 was released today, with the aforementioned note on AAC incompatibility.
- [NetworkInterceptor Wiki](https://github.com/SlimeDog/NetworkInterceptor/wiki)
- [NetworkInterceptor Wiki/Technical-Details](https://github.com/SlimeDog/NetworkInterceptor/wiki/Technical-Details)

We remain open to working with AAC developers to resolve this issue.

**Comment by OpticFusion1** [comment]
Any SM causes it to disable, including my own

**Comment by SlimeDog** [comment]
> Any SM causes it to disable, including my own

I have no idea what SM you mean, but (I hope) it has no impact on NetworkInterceptor.

If you mean that a SM in one of your resources also causes AAC to disable itself, that should be noted in the AAC issue, not this issue.

**Comment by OpticFusion1** [comment]
Yea, it's an AAC issue.
Really not much that can be done in that regard though, either NI and other resource have to have the ability to turn its own security-manager off or AAC has to stop disabling its self if it can't set a security-manager, not that AAC's security-manager is that useful anyways since there's other ways to get what it connects to

**Comment by SlimeDog** [comment]
AAC was last updated July 2021, and is an InactiveResource on SpigotMC. NetworkInterceptor integration is no longer supported.
